service: local-microservice

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}

configValidationMode: error